name: Build and Memory Leak Checker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies and install Valgrind
        run: sudo apt-get update && sudo apt-get install -y build-essential valgrind

      - name: Build
        run: make

      #      - name: Memory Leak Check (on basic example class)
      #        run: valgrind ./bin/runtime -b examples/basic/main.class --leak-check=FULL

      # - name: Parse/lex Memory Leak Check (new feature toggle)
      #   run: valgrind ./bin/runtime -l examples/lang/test.rvm --leak-check=FULL
