name: Build and Memory Leak Checker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies and install Valgrind
        run: sudo apt-get update && sudo apt-get install -y build-essential valgrind

      - name: Build
        run: make

      - name: Language file to RVMC (new feature toggle)
        run: valgrind ./bin/runtime -l examples/lang/test.rvm --track-origin=yes --leak-check=FULL --error-exitcode=1

      - name: Interpretation of binary (RVMC) file
        run: valgrind ./bin/runtime -b examples/lang/test.rvmc --track-origin=yes --leak-check=FULL --error-exitcode=1
