name: Versioned Release

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2
        if: matrix.platform == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-toolchain make
          update: true

      - name: Extract intermediate language version number
        id: get_version
        run: |
          MAJOR_VERSION=$(grep '#define IL_MAJOR_VERSION' ./src/common_properties.h | awk '{print $3}')
          MINOR_VERSION=$(grep '#define IL_MINOR_VERSION' ./src/common_properties.h | awk '{print $3}')
          echo "VERSION=$MAJOR_VERSION.$MINOR_VERSION" >> $GITHUB_ENV
          echo "Version: $MAJOR_VERSION.$MINOR_VERSION"

      - name: Build binary
        run: make
        shell: bash
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Archive Binary
        run: |
          mkdir -p dist
          if [ "${{ matrix.platform }}" == "windows-latest" ]; then
            zip -r "dist/rvm-${{ env.VERSION }}-windows.zip" ./bin/*
          else
            tar -czvf "dist/rvm-${{ env.VERSION }}-${{ matrix.platform }}.tar.gz" ./bin/*
          fi

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
          git push origin v${{ env.VERSION }} || true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          files: |
            dist/*
          body: |
            Release v${{ env.VERSION }}
            - Major version: ${{ env.MAJOR_VERSION }}
            - Minor version: ${{ env.MINOR_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
